# Generated by Django 4.2 on 2024-02-01 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('icon', models.CharField(default='location-pin', max_length=100)),
                ('marker_color', models.CharField(default='red', max_length=50)),
                ('inside_planner', models.BooleanField(default=False)),
                ('descriptions', models.TextField()),
                ('price', models.FloatField()),
                ('destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_manager.destinations')),
            ],
        ),
        migrations.CreateModel(
            name='Planner_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_manager.destinations')),
            ],
        ),
        migrations.CreateModel(
            name='Planner_Table_Date',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('planner_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_manager.planner_date')),
            ],
        ),
        migrations.CreateModel(
            name='Tiktok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_manager.destinations')),
            ],
        ),
        migrations.CreateModel(
            name='Planner_Table_Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField()),
                ('color_label', models.TextField()),
                ('destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_manager.destinations')),
                ('location_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_manager.location_address')),
                ('planner_table_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_manager.planner_table_date')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fly_cost', models.FloatField()),
                ('description', models.TextField()),
                ('destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_manager.destinations')),
            ],
        ),
    ]
