# Generated by Django 4.2 on 2024-02-01 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner_table_date',
            name='destinations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel_manager.destinations'),
            preserve_default=False,
        ),
    ]
