# Generated by Django 4.2 on 2024-01-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_manager', '0002_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_address',
            name='icon',
            field=models.CharField(default='location-pin', max_length=100),
        ),
    ]
