# Generated by Django 4.2 on 2024-02-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_manager', '0002_planner_table_date_destinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner_table_date',
            name='destinations',
        ),
        migrations.RemoveField(
            model_name='planner_table_descriptions',
            name='destinations',
        ),
    ]
