# Generated by Django 4.2 on 2024-02-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_manager', '0004_alter_documents_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_address',
            name='descriptions',
            field=models.TextField(default='Attration'),
        ),
        migrations.AlterField(
            model_name='location_address',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
