# Generated by Django 4.2 on 2024-01-28 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_manager', '0004_location_address_marker_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_manager.destinations')),
            ],
        ),
    ]
