# Generated by Django 4.2 on 2024-01-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_manager', '0005_planner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planner',
            new_name='Planner_Date',
        ),
        migrations.CreateModel(
            name='Planner_Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('descriptions', models.TextField()),
                ('planner_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_manager.planner_date')),
            ],
        ),
    ]
