# Generated by Django 4.2 on 2024-01-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_manager', '0006_rename_planner_planner_date_planner_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='information',
            name='longitude',
        ),
        migrations.AddField(
            model_name='destinations',
            name='latitude',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='longitude',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
