# Generated by Django 4.2 on 2024-02-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_manager', '0006_alter_destinations_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=512)),
                ('price', models.FloatField(default=0)),
                ('destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_manager.destinations')),
            ],
        ),
    ]
