# Generated by Django 4.2 on 2024-01-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_manager', '0007_remove_information_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_address',
            name='inside_planner',
            field=models.BooleanField(default=False),
        ),
    ]
