# Generated by Django 4.2 on 2024-03-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_manager', '0007_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
